SELECT * 
FROM person.Person;

SELECT Title
FROM person.Person;

SELECT*
FROM person.Person

/*DESAFIO 1*/

/*A EQUIPE DE MARKETING PRECISA DE FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS
DE SEUS CLIENTES E PRESCISA DO NOME E SOBRENOME  DE TODOS OS CLIENTES 
QUE ESTÃO CADASTRADOS NO SISTEMA */

SELECT FirstName 
FROM Person.Person
ORDER BY FirstName;

SELECT FirstName,LastName  
FROM Person.Person
ORDER BY FirstName;